//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleParking
    {
        public int VehicleParkingID { get; set; }
        public Nullable<int> ParkingZoneID { get; set; }
        public Nullable<int> ParkingSpaceID { get; set; }
        public string RegistrationNumber { get; set; }
        public System.DateTime BookingDateTime { get; set; }
        public Nullable<System.DateTime> ReleaseDateTime { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual ParkingZone ParkingZone { get; set; }
    }
}
